{% set name = "flake8-colors" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a2c14ace214e22ba07870e25efc4ccd640f21227de9820482ea73b68343ee96

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python
  entry_points:
    - flake8-colors = flake8_colors:ColorFormatter

requirements:
  host:
    - flake8 >3.0.0
    - pip
    - python
    - setuptools
  run:
    - flake8 >3.0.0
    - python

test:
  imports:
    - flake8_colors

about:
  home: https://github.com/and3rson/flake8-colors
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Error highlight plugin for Flake8.

extra:
  recipe-maintainers:
    - marcelotrevisani
